spring:
  application:
    name: hello-world
  sleuth:
    async:
      enabled: false

server:
  port : 9007
  servlet:
    context-path: /hello-world

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true


ssl:
  truststore_location: ${project.basedir}/selfsignedcertificate.p12
  truststore_password: changeit

  keystore_location: ${project.basedir}/selfsignedcertificate.p12
  keystore_password: changeit
  key_password: changeit

mongo:
  host: localhost
  port: 27017
  database: test
  user: someuser
  password: somepassword


kafka:
  bootstrapservers: localhost:443
  producer:
    topic: x
  consumer:
    topic: xx
    groupId: xx

sftp:
  host: x
  port: x
  username: x
  password: x
  knowHostPublicKey: x
  sftpfilepath : x
  downloaddir: x

# Please make sure you configure the connector properties, ssl properties before turning on the connector
connector:
  enable:
    mongo: true
    kafka_producer: false
    kafka_consumer: true
    sftp: false


# Set this property to true if you want to enable logging to MongoDB and also make sure mongo connector is enabled
auditing:
  enable: true
